version: "3.3"
services:
  db:
    container_name: nedrex-web-db_dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: reposcape
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: reposcaper
      MYSQL_PASSWORD: nedrex
    volumes:
      - dev_nedrex-db-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE
  web:
    container_name: nedrex-web-frontend_dev
    image: andimajore/nedrex_repo:web_arenal-dev
    build: frontend
    ports:
      - "8061:8080"
    restart: on-failure
  server:
    container_name: nedrex-web-backend_dev
    image: andimajore/nedrex_repo:server_arenal-dev
    depends_on:
      - "db"
    build: backend
    environment:
      - spring_profiles_active=arenal_dev
    volumes:
      - dev_nedrex-cache-volume:/etc/data/db
      - dev_nedrex-usr-volume:/etc/data/usr
    ports:
      - "8062:8090"
    restart: on-failure
volumes:
  dev_nedrex-db-volume:
    external: true
  dev_nedrex-usr-volume:
    external: true
  dev_nedrex-cache-volume:
    external: true
