package de.exbio.reposcapeweb.db.entities.edges;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;
import de.exbio.reposcapeweb.db.entities.RepoTrialEdge;
import de.exbio.reposcapeweb.db.entities.ids.PairId;
import de.exbio.reposcapeweb.utils.Pair;
import de.exbio.reposcapeweb.utils.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

/**
 * Entity class for a transitive edge "GeneAssociatedWithDisorder" (gene_associated_with_disorder in db).
 * <i>These entries are derived by combining {@link ProteinAssociatedWithDisorder} and {@link ProteinEncodedBy} for giving the opportunity for better data discovery.</i>
 * The attributes primaryDomainIds of {@link GeneAssociatedWithDisorder#sourceDomainId} and {@link GeneAssociatedWithDisorder#targetDomainId} contain the ids of the {@link de.exbio.reposcapeweb.db.entities.nodes.Gene} (source) and a identified association with a {@link de.exbio.reposcapeweb.db.entities.nodes.Disorder} (target).
 * These primaryDomainIds from RepoTrial are converted to numeric node ids autogenerated on insertion of the nodes into the db.
 * Further the "type" attribute is also not included in the database, having only one possible value.
 * The class extends the {@link RepoTrialEdge} abstract class, for some methods used during import of the different RepoTrial entities.
 *
 * @author Andreas Maier
 */
@Entity
@Table(name = "gene_associated_with_disorder")
public class GeneAssociatedWithDisorder extends RepoTrialEdge implements Serializable {

    @Transient
    @JsonIgnore
    private final Logger log = LoggerFactory.getLogger(GeneAssociatedWithDisorder.class);

    @JsonIgnore
    @EmbeddedId
    private PairId id;

    @Transient
    @JsonIgnore
    public final static HashSet<String> attributes = new HashSet<>(Arrays.asList("targetDomainId", "type", "sourceDomainId", "score", "assertedBy"));


    @Transient
    private String targetDomainId;
    @Transient
    private String sourceDomainId;

    private String score;

    private String assertedBy;


    public static String[] getListAttributes() {
        return new String[]{"targetDomainId", "type", "sourceDomainId", "score", "assertedBy"};
    }

    @Override
    public HashMap<String, String> getAsMap() {
        HashMap<String,String> values = new HashMap<>();
        values.put("targetDomainId",targetDomainId);
        values.put("sourceDomainId",sourceDomainId);
        values.put("type",getType());
        values.put("score",score);
        values.put("assertedBy",assertedBy);
        return values;
    }

    @Override
    public HashMap<String, String> getAsMap(HashSet<String> attributes) {
        HashMap<String,String> values = new HashMap<>();
        getAsMap().forEach((k,v)->{
            if(attributes.contains(k))
                values.put(k,v);
        });
        return values;
    }

    public GeneAssociatedWithDisorder() {
    }

    public String getTargetDomainId() {
        return targetDomainId;
    }

    public String getSourceDomainId() {
        return sourceDomainId;
    }

    @JsonGetter
    public String getType() {
        return "GeneAssociatedWithDisorder";
    }

    public String getScore() {
        return score;
    }

    @JsonSetter
    public void setType(String type) {
    }

    public List<String> getAssertedBy() {
        return StringUtils.stringToList(assertedBy);
    }

    public void setAssertedBy(List<String> assertedBy) {
        this.assertedBy = StringUtils.listToString(assertedBy);
    }

    public void setValues(GeneAssociatedWithDisorder other) {
        this.sourceDomainId = other.sourceDomainId;
        this.targetDomainId = other.targetDomainId;
        this.assertedBy = other.assertedBy;
        this.score = other.score;
    }

    @Override
    public PairId getPrimaryIds() {
        return id;
    }

    public void setId(PairId id) {
        this.id = id;
    }

    @Override
    public Pair<String, String> getIdsToMap() {
        return new Pair<>(sourceDomainId, targetDomainId);
    }
}
