package de.exbio.reposcapeweb.db.entities.edges;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonSetter;
import de.exbio.reposcapeweb.db.entities.RepoTrialEdge;
import de.exbio.reposcapeweb.db.entities.ids.PairId;
import de.exbio.reposcapeweb.utils.Pair;
import de.exbio.reposcapeweb.utils.RepoTrialUtils;
import de.exbio.reposcapeweb.utils.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;


/**
 * Entity class for the RepoTrial edge "ProteinInteractsWithProtein" (protein_interacts_with_protein in db).
 * The attributes primaryDomainIds of {@link ProteinInteractsWithProtein#memberOne} and {@link ProteinInteractsWithProtein#memberTwo} contain the ids of two {@link de.exbio.reposcapeweb.db.entities.nodes.Protein} objects connected by their interaction property.).
 * These primaryDomainIds from RepoTrial are converted to numeric node ids autogenerated on insertion of the nodes into the db.
 * Further the "type" attribute is also not included in the database, having only one possible value.
 * The class extends the {@link RepoTrialEdge} abstract class, for some methods used during import of the different RepoTrial entities.
 *
 * @author Andreas Maier
 */
@Entity
@Table(name = "protein_interacts_with_protein")
public class ProteinInteractsWithProtein extends RepoTrialEdge implements Serializable {


    @Transient
    @JsonIgnore
    private final Logger log = LoggerFactory.getLogger(ProteinInteractsWithProtein.class);

    @JsonIgnore
    @EmbeddedId
    private PairId id;

    @Transient
    @JsonIgnore
    public static HashSet<String> sourceAttributes;

    @Transient
    @JsonIgnore
    public static String[] allAttributes;

    @Transient
    @JsonIgnore
    public static String[] allAttributeTypes;

    @Transient
    @JsonIgnore
    public static String[] attributeLabels;

    @Transient
    @JsonIgnore
    public static HashMap<String,String> name2labelMap;

    @Transient
    @JsonIgnore
    public static HashMap<String,String> label2NameMap;

    @Transient
    @JsonIgnore
    public static Boolean[] idAttributes;

    @Transient
    @JsonIgnore
    public static String[] listAttributes;

    public static String[] getListAttributes() {
        return listAttributes;
    }
    @Transient
    private String memberOne;
    @Transient
    private String memberTwo;
    @Column(columnDefinition = "TEXT")
    private String methods;

    @Transient
    private String nodeOne;
    @Transient
    private String nodeTwo;

//    private String sourceDatabases;
    private String assertedBy;
    private String evidenceTypes;

    public ProteinInteractsWithProtein() {
    }

    @Override
    public HashMap<String, Object> getAsMap() {
        HashMap<String, Object> values = new HashMap<>();
//        values.put("databases", getDatabases());
        values.put("assertedBy", getAssertedBy());
        values.put("memberOne", getMemberOne());
        values.put("memberTwo", getMemberTwo());
        values.put("idOne", id.getId1());
        values.put("idTwo", id.getId2());
        values.put("node1", RepoTrialUtils.adjustLabels(nodeOne));
        values.put("node2",RepoTrialUtils.adjustLabels(nodeTwo));
        values.put("evidenceTypes", getEvidenceTypes());
        values.put("type", getType());
        values.put("id", id.getId1() + "-" + id.getId2());
        values.put("methods",getMethods());
        return values;
    }

    public void setNodeNames(String node1, String node2){
        nodeOne=node1;
        nodeTwo=node2;
    }

    @Override
    public HashMap<String, Object> getAsMap(HashSet<String> attributes) {
        HashMap<String, Object> values = new HashMap<>();
        getAsMap().forEach((k, v) -> {
            if (attributes.contains(k))
                values.put(k, v);
        });
        return values;
    }

    public void flipIds(){
        this.id.flipIds();
        String tmp = memberOne;
        memberOne=memberTwo;
        memberTwo=tmp;
    }


    public String getMemberOne() {
        return memberOne;
    }

    public String getMemberTwo() {
        return memberTwo;
    }

    @JsonGetter
    public String getType() {
        return "ProteinInteractsWithProtein";
    }

    @JsonSetter
    public void setType(String type) {
    }

    public static void setUpNameMaps() {
        label2NameMap=new HashMap<>();
        name2labelMap = new HashMap<>();
        for (int i = 0; i < allAttributes.length; i++) {
            label2NameMap.put(allAttributes[i],attributeLabels[i]);
            name2labelMap.put(attributeLabels[i], allAttributes[i]);
        }
    }

    public List<String> getMethods() {
        return StringUtils.stringToList(methods);
    }

    public void setMethods(List<String> methods) {
        this.methods = StringUtils.listToString(methods);
    }

//    public List<String> getDatabases() {
//        return StringUtils.stringToList(sourceDatabases);
//    }
//
//    public void setDatabases(List<String> databases) {
//        this.sourceDatabases = StringUtils.listToString(databases);
//    }

    public List<String> getAssertedBy() {
        return StringUtils.stringToList(assertedBy);
    }

    public void setAssertedBy(List<String> databases) {
        this.assertedBy = StringUtils.listToString(databases);
    }

    public List<String> getEvidenceTypes() {
        return StringUtils.stringToList(evidenceTypes);
    }

    public void setEvidenceTypes(List<String> evidenceTypes) {
        this.evidenceTypes = StringUtils.listToString(evidenceTypes);
    }

    public void setValues(ProteinInteractsWithProtein other) {
//        this.sourceDatabases = other.sourceDatabases;
        this.assertedBy = other.assertedBy;
        this.evidenceTypes = other.evidenceTypes;
        this.memberOne = other.memberOne;
        this.memberTwo = other.memberTwo;
        this.methods = other.methods;
    }

    @Override
    public PairId getPrimaryIds() {
        return id;
    }

    public void setId(PairId id) {
        this.id = id;
    }

    @Override
    public Pair<String, String> getIdsToMap() {
        return new Pair<>(memberOne, memberTwo);
    }

    public void setMemberOne(String memberOne) {
        this.memberOne = memberOne;
    }

    public void setMemberTwo(String memberTwo) {
        this.memberTwo = memberTwo;
    }
}
