package de.exbio.reposcapeweb.filter;

public enum FilterType {
    ID, NAME,ICD10, SYNONYM, IUPAC, SYMBOL, ORIGIN,
    DESCRIPTION, INDICATION, COMMENTS,
    TYPE, CATEGORY, GROUP, CHROMOSOME, UMBRELLA_DISORDER
}
