version: "3.3"
services:
  db:
    container_name: nedrex-web-db
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
#    restart: on-failure
    environment:
      MYSQL_DATABASE: reposcape
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: reposcaper
      MYSQL_PASSWORD: nedrex
    ports:
      - "3306:3306"
    volumes:
      - nedrex-db-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE
  server:
    container_name: nedrex-web-backend
    image: andimajore/nedrex_repo:dev
    depends_on:
      - "db"
    build: backend
    environment:
      - spring_profiles_active=dev
    volumes:
      - nedrex-cache-volume:/etc/data/db
      - nedrex-usr-volume:/etc/data/usr
    ports:
      - "8090:8090"
 #   restart: on-failure
volumes:
  nedrex-db-volume:
    external: true
  nedrex-usr-volume:
    external: true
  nedrex-cache-volume:
    external: true
