version: "3.3"
services:
  db:
    container_name: nedrex-web-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: reposcape
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: reposcaper
      MYSQL_PASSWORD: repotrial
    volumes:
      - nedrex-db-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE
  web:
    container_name: nedrex-web-view
    image: andimajore/nedrex_repo:web
    build: frontend
    ports:
      - "8024:8080"
    restart: on-failure
  server:
    container_name: nedrex-web-server
    image: andimajore/nedrex_repo:server
    depends_on:
      - "db"
    build: backend
    environment:
       - spring_profiles_active=prod
    volumes:
      - nedrex-cache-volume:/etc/data/db
      - nedrex-usr-volume:/etc/data/usr
    ports:
      - "8034:8090"
    restart: on-failure
volumes:
  nedrex-db-volume:
  nedrex-usr-volume:
  nedrex-cache-volume:
